server:
  port: 8207

spring:
  application:
    name: service-order

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 8.130.170.8
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

  data:
    mongodb:
      #uri: mongodb://admin:123456@localhost:27017/yygh_hosp?authSource=admin&authMechanism=SCRAM-SHA-1
      uri: mongodb://admin:123456@8.130.170.8:27017/yygh_hosp?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: false

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.170.8:8848

  #rabbitmq地址
  rabbitmq:
    host: 8.130.170.8
    port: 5672
    username: guest
    password: guest

weixin:
  appid: wx74862e0dfcf69954 #关联的公众号appid
  partner: 1558950191 #商户号
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb #商户key
  cert: cert/apiclient_cert.p12

mybatis-plus:
  mapper-locations: classpath*:/mapper/order/*.xml







