server:
  port: 8206
spring:
  application:
    name: service-oss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 8.130.170.8
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.170.8:8848


aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tSoiyGFg97sGXHAdRnU
    secret: 7RjnQmY8Qs4k9oLvkQ9j9jpIcqas1d
    bucket: yygh-oss-study

