server:
  port: 80

spring:
  application:
    name: service-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          #设置路由断言,代理servicerId为auth-service的/auth/路径
          predicates: Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates: Path=/*/cmn/**

