server:
  port: 80

spring:
  application:
    name: service-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.170.8:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          #设置路由断言,代理servicerId为auth-service的/auth/路径
          predicates: Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates: Path=/*/cmn/**
        - id: service-user
          uri: lb://service-user
          predicates: Path=/*/user/**
        - id: service-eamil
          uri: lb://service-email
          predicates: Path=/*/email/**
        - id: service-sms
          uri: lb://service-sms
          predicates: Path=/*/sms/**
        - id: service-user
          uri: lb://service-user
          predicates: Path=/*/ucenter/**
        - id: service-oss
          uri: lb://service-oss
          predicates: Path=/*/oss/**
        - id: service-order
          uri: lb://service-order
          predicates: Path=/*/order/**
        - id: service-statistics
          uri: lb://service-statistics
          predicates: Path=/*/statistics/**

